### ISSUE TITLE
MT "no data" for about a minute once a read node gets queries

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#610] opened 2017-04-19 21:31 UTC
during 0.7.1 upgrade to 0.7.1-61-gbe64803 i notice the following:

cluster is fine while new instance catches up backlog from kafka, slowly decreasing partition lag and priority metrics
the moment priority hits 0 the instance gets requests
for roughly a minute, the instance is kindof flakey and returns many (all?) requests without data
afterwards it behaves fine.
see on our monitoring server /dashboard/db/metrictank-0-7-0-beta1-k8s-cluster?orgId=1&from=1492632741050&to=1492633819384&var-datasource=raintankPOC&var-environment=12574-ops&var-instance=mt-read00-12574-small-ops-1363878596-xvmzp
currently deploying 0.7.1 again to see if it has the same issue.

**Comment by Dieterbe** [comment] 2017-04-19 22:25
just brought up 2 instances on 0.7.1 and they did not exhibit this issue.

**Comment by woodsaj** [comment] 2017-04-21 21:32
by default the instance will start handling requests when priority drops below max-prority https://github.com/raintank/metrictank/blob/master/metrictank-sample.ini#L192

on hosted-metrics the default max-priority is 60

**Comment by Dieterbe** [comment] 2017-04-21 21:54
note that 0.7.1 did not have the issue, nor does 0.7.1-22-g86860d8 which is the last version before my api code got merged.  so i think it's related to my api code, perhaps 69b8cf7a7ead4527e354ac4fb45a04937b0ff7a5

**Comment by woodsaj** [comment] 2017-04-21 23:31
I think the problem is that 60 is too high for max-priority.   The priority of 60 means that at the current ingest rate the instance will clear the backlog in 60seconds.   However, at startup, the instances replays the backlog as fast as it can.  Lets assume at 5x the normal ingest rate (it is actually probably more then this).

so if the node is going to take 60seconds to clear the backlog when processing at 5x realtime. then the newest data the instances has is 5minutes old.

I think the reason for the intermittent behavior is because: 
*  the prio is based on the slowest partition.   As partitions complete, the ingest rate will drop.  So if 7/8 partitions complete but 1 partition is still lagging, then when that 1 partition is 60seconds from catching up requests can be handled and at least 7/8ths of the data will be returned. 
* the priority is only updated once every 10seconds.

**Comment by woodsaj** [comment] 2017-04-26 21:53
this was almost certainly due to the msgp (go-generate) issue fixed in https://github.com/raintank/metrictank/pull/617

**Closed** 2017-04-27 01:00 UTC
