### ISSUE TITLE
nilpointer in gzip.go

### ISSUE THREAD

**Issue by Dieterbe** [raintank/metrictank#642] opened 2017-05-23 13:51 UTC
```
[Macaron] 2017-05-23 13:49:23: Started POST /getdata for 172.19.0.19
[Macaron] 2017-05-23 13:49:23: Started POST /index/find for 172.19.0.19
[Macaron] 2017-05-23 13:49:23: Started POST /render/ for 172.20.0.14
[Macaron] PANIC: runtime error: invalid memory address or nil pointer dereference
/usr/local/go/src/runtime/panic.go:489 (0x42a57f)
/usr/local/go/src/runtime/panic.go:63 (0x42942e)
/usr/local/go/src/runtime/signal_unix.go:290 (0x43f8ff)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/raintank/gziper/gzip.go:104 (0x9b2655)
/usr/local/go/src/runtime/asm_amd64.s:514 (0x457088)
/usr/local/go/src/runtime/panic.go:489 (0x42a57f)
/usr/local/go/src/runtime/panic.go:28 (0x4291fe)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/expr/func_sumseries.go:46 (0x9957ab)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/expr/func_aliasbynode.go:30 (0x98f558)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/expr/plan.go:212 (0x99b07b)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/api/graphite.go:568 (0x9c1446)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/api/graphite.go:206 (0x9bcc83)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/api/routes.go:43 (0x9c77f2)
/usr/local/go/src/runtime/asm_amd64.s:516 (0x4571a6)
/usr/local/go/src/reflect/value.go:434 (0x4a322f)
/usr/local/go/src/reflect/value.go:302 (0x4a27f4)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9309ff)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9303ca)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x94de52)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x94dd76)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/api/middleware/stats.go:72 (0x96c367)
/usr/local/go/src/runtime/asm_amd64.s:514 (0x457088)
/usr/local/go/src/reflect/value.go:434 (0x4a322f)
/usr/local/go/src/reflect/value.go:302 (0x4a27f4)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9309ff)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9303ca)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x94de52)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x94dd76)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/raintank/gziper/gzip.go:73 (0x9b2b5c)
/usr/local/go/src/runtime/asm_amd64.s:514 (0x457088)
/usr/local/go/src/reflect/value.go:434 (0x4a322f)
/usr/local/go/src/reflect/value.go:302 (0x4a27f4)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9309ff)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9303ca)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x94de52)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x94dd76)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/recovery.go:161 (0x95f77b)
/usr/local/go/src/runtime/asm_amd64.s:514 (0x457088)
/usr/local/go/src/reflect/value.go:434 (0x4a322f)
/usr/local/go/src/reflect/value.go:302 (0x4a27f4)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9309ff)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9303ca)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x94de52)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/context.go:104 (0x94dd76)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/logger.go:43 (0x95ea34)
/usr/local/go/src/runtime/asm_amd64.s:514 (0x457088)
/usr/local/go/src/reflect/value.go:434 (0x4a322f)
/usr/local/go/src/reflect/value.go:302 (0x4a27f4)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/go-macaron/inject/inject.go:177 (0x9309ff)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/github.com/go-macaron/inject/inject.go:137 (0x9303ca)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/context.go:113 (0x94de52)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/router.go:184 (0x960a49)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/router.go:286 (0x959eed)
/home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/vendor/gopkg.in/macaron.v1/macaron.go:177 (0x9522bc)
/usr/local/go/src/net/http/server.go:2568 (0x6db192)
/usr/local/go/src/net/http/server.go:1825 (0x6d7562)
/usr/local/go/src/runtime/asm_amd64.s:2197 (0x4597d1)
[Macaron] 2017-05-23 13:49:23: Completed /render 500 Internal Server Error in 57.719013ms
```

**Comment by woodsaj** [comment] 2017-05-23 15:41
This looks like a bug in the raintank/gziper library. Triggered when the responseWriter is closed before anything tried to write to it.

opened https://github.com/raintank/gziper/issues/2

**Comment by woodsaj** [comment] 2017-05-23 15:43
Though my guess is that this was caused by a panic at /home/ubuntu/.go_workspace/src/github.com/raintank/metrictank/expr/func_sumseries.go:46

**Comment by woodsaj** [comment] 2017-05-23 16:33
The raintank/gziper issues has been fixed in https://github.com/raintank/gziper/commit/ad70bdb176fa32c61c29d21cd053bdfd9f0ec329

But I also confirmed that the bug was due to using macaron.Recovery() which handles panics.  So i am certain that you will find that a panic is being generated in func_sumseries.go:46

**Closed** 2017-05-23 22:14 UTC
